# Services
services:

    # PHP Service
    php:
        build:
            dockerfile: php-dockerfile
        container_name: php8
        volumes:
            - './public:/var/www/html'
        depends_on:
            - mariadb
        networks:
            - app-network

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 80:80
        links:
            - 'php'
        volumes:
            - './public:/var/www/html'
            - './nginx-conf:/etc/nginx/conf.d'
        depends_on:
            - php
        networks:
            - app-network

    # MariaDB Service
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
          - ./data:/var/lib/mysql
        command: 
          --max-allowed-packet=100M # added option to allow large imports
        networks:
            - app-network
  
networks:
    app-network:
        driver: bridge